/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chyss_myapplication_widget_jni_MyJni */

#ifndef _Included_com_chyss_myapplication_widget_jni_MyJni
#define _Included_com_chyss_myapplication_widget_jni_MyJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chyss_myapplication_widget_jni_MyJni
 * Method:    fromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chyss_myapplication_widget_jni_MyJni_fromNative
  (JNIEnv *env, jclass jc)
  {
        return env -> NewStringUTF("COME FROM NATIVE");
  }

#ifdef __cplusplus
}
#endif
#endif

